package models

// only difference between quoteDetails in quote request vs save quote is quoteId
type QuoteDetails struct {
	BillingAddress                   Address                    `json:"billingAddress,omitempty" dynamodbav:"billingAddress"`
	OriginShippingDetails            OriginShippingDetails      `json:"originShippingDetails,omitempty" dynamodbav:"originShippingDetails"`
	DestinationShippingDetails       DestinationShippingDetails `json:"destinationShippingDetails,omitempty" dynamodbav:"destinationShippingDetails"`
	ShipmentItems                    []*ShipmentItem            `json:"shipmentItems,omitempty" dynamodbav:"shipmentItems"`
	FreightCharge                    int                        `json:"freightCharge,omitempty" dynamodbav:"freightCharge"`
	ShipmentID                       string                     `json:"shipmentId,omitempty" dynamodbav:"shipmentId"`
	IsInsuredShipment                bool                       `json:"isInsuredShipment,omitempty" dynamodbav:"isInsuredShipment"`
	InsuranceEditShipmentData        interface{}                `json:"insuranceEditShipmentData,omitempty" dynamodbav:"insuranceEditShipmentData"`
	CarrierCode                      string                     `json:"carrierCode,omitempty" dynamodbav:"carrierCode"`
	ReferenceNumberInfo              *ReferenceNumberInfo       `json:"referenceNumberInfo,omitempty" dynamodbav:"referenceNumberInfo"`
	EmergencyContactPerson           *EmergencyContactPerson    `json:"emergencyContactPerson,omitempty" dynamodbav:"emergencyContactPerson"`
	ServiceLevelCode                 string                     `json:"serviceLevelCode,omitempty" dynamodbav:"serviceLevelCode"`
	IsAdminQuote                     bool                       `json:"isAdminQuote,omitempty" dynamodbav:"isAdminQuote"`
	ReferenceID                      string                     `json:"referenceId,omitempty" dynamodbav:"referenceId"`
	IsFromSavedQuote                 bool                       `json:"isFromSavedQuote,omitempty" dynamodbav:"isFromSavedQuote"`
	IsFromShipment                   bool                       `json:"isFromShipment,omitempty" dynamodbav:"isFromShipment"`
	SpecialInstructionDefaultText    string                     `json:"specialInstructionDefaultText,omitempty" dynamodbav:"specialInstructionDefaultText"`
	ServiceType                      int                        `json:"serviceType,omitempty" dynamodbav:"serviceType"`
	IsShowVLTLToggle                 bool                       `json:"isShowVLTLToggle,omitempty" dynamodbav:"isShowVLTLToggle"`
	LinearFeet                       interface{}                `json:"linearFeet,omitempty" dynamodbav:"linearFeet"`
	CurrentLinearFeet                interface{}                `json:"currentLinearFeet,omitempty" dynamodbav:"currentLinearFeet"`
	IsVLTLResponse                   bool                       `json:"isVLTLResponse,omitempty" dynamodbav:"isVLTLResponse"`
	IsAutoEmailTrackingEnabled       bool                       `json:"isAutoEmailTrackingEnabled,omitempty" dynamodbav:"isAutoEmailTrackingEnabled"`
	IsManualDispatchSettingEnabled   bool                       `json:"isManualDispatchSettingEnabled,omitempty" dynamodbav:"isManualDispatchSettingEnabled"`
	IsMetricMeasurementEnabled       bool                       `json:"isMetricMeasurementEnabled,omitempty" dynamodbav:"isMetricMeasurementEnabled"`
	EquipmentTypeID                  interface{}                `json:"equipmentTypeId,omitempty" dynamodbav:"equipmentTypeId"`
	EquipmentTypeName                interface{}                `json:"equipmentTypeName,omitempty" dynamodbav:"equipmentTypeName"`
	EquipmentSize                    interface{}                `json:"equipmentSize,omitempty" dynamodbav:"equipmentSize"`
	TargetRate                       interface{}                `json:"targetRate,omitempty" dynamodbav:"targetRate"`
	ShipmentNote                     interface{}                `json:"shipmentNote,omitempty" dynamodbav:"shipmentNote"`
	IsHotLoad                        bool                       `json:"isHotLoad,omitempty" dynamodbav:"isHotLoad"`
	OpportunityID                    interface{}                `json:"opportunityId,omitempty" dynamodbav:"opportunityId"`
	OptionID                         interface{}                `json:"optionId,omitempty" dynamodbav:"optionId"`
	TruckloadAccessorials            interface{}                `json:"truckloadAccessorials,omitempty" dynamodbav:"truckloadAccessorials"`
	QuoteID                          interface{}                `json:"quoteId,omitempty" dynamodbav:"quoteId"`
	QuoteOpportunityID               interface{}                `json:"quoteOpportunityId,omitempty" dynamodbav:"quoteOpportunityId"`
	ShipmentTruckloadID              interface{}                `json:"shipmentTruckloadId,omitempty" dynamodbav:"shipmentTruckloadId"`
	IsReRunShipment                  bool                       `json:"isReRunShipment,omitempty" dynamodbav:"isReRunShipment"`
	SpecialInstruction               interface{}                `json:"specialInstruction,omitempty" dynamodbav:"specialInstruction"`
	CarriersNotInQuote               CarrierNotInQuote          `json:"carriersNotInQuote,omitempty" dynamodbav:"carriersNotInQuote"`
	QuoteKey                         interface{}                `json:"quoteKey,omitempty" dynamodbav:"quoteKey"`
	IsExistConnectedCarriers         bool                       `json:"isExistConnectedCarriers,omitempty" dynamodbav:"isExistConnectedCarriers"`
	IsCargoInsuranceToogleOn         bool                       `json:"isCargoInsuranceToogleOn,omitempty" dynamodbav:"isCargoInsuranceToogleOn"`
	CargoInsuranceQuoteInfo          *CargoInsuranceQuoteInfo   `json:"cargoInsuranceQuoteInfo,omitempty" dynamodbav:"cargoInsuranceQuoteInfo"`
	QuoteErrors                      []interface{}              `json:"quoteErrors,omitempty" dynamodbav:"quoteErrors"`
	UnusedCommodities                []interface{}              `json:"unusedCommodities,omitempty" dynamodbav:"unusedCommodities"`
	CustomerCarrierID                int                        `json:"customerCarrierId,omitempty" dynamodbav:"customerCarrierId"`
	IntegratedLocationAccountNumber1 interface{}                `json:"integratedLocationAccountNumber1,omitempty" dynamodbav:"integratedLocationAccountNumber1"`
	TimeCreated                      interface{}                `json:"timeCreated,omitempty" dynamodbav:"timeCreated"`
	OriginCode                       interface{}                `json:"originCode,omitempty" dynamodbav:"originCode"`
	TruckloadCapacityProviders       []string                   `json:"truckloadCapacityProviders,omitempty" dynamodbav:"truckloadCapacityProviders"`
	IsVicsBolShipment                bool                       `json:"isVicsBolShipment,omitempty" dynamodbav:"isVicsBolShipment"`
	TotalWeight                      string                     `json:"totalWeight,omitempty" dynamodbav:"totalWeight"`
	CurrentEquipmentSize             interface{}                `json:"currentEquipmentSize,omitempty" dynamodbav:"currentEquipmentSize"`
	QuoteDate                        string                     `json:"quoteDate,omitempty" dynamodbav:"quoteDate"`
}
