package test

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/goccy/go-json"
)

func Test_SaveBOL(t *testing.T) {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl 'https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/Quote/SaveBolAsPdf' \
	//   -H 'authority: rapidshipltl.mycarriertms.com' \
	//   -H 'accept: application/json' \
	//   -H 'accept-language: en-US,en;q=0.9' \
	//   -H 'access-control-expose-headers: Content-Disposition' \
	//   -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImthbmRlbHN1cmVuQGdtYWlsLmNvbSIsInJvbGUiOlsiTXlDYXJyaWVyX1NoaXAiLCJNeUNhcnJpZXJfTWFuYWdlQ29tcGFueSIsIkNhbkFjY2Vzc0hvbWVQYWdlIiwiQ2FuVXNlUXVvdGVQYWdlIiwiQ2FuVXNlU2hpcG1lbnRMaXN0UGFnZSIsIkNhblVzZUFkZHJlc3NCb29rUGFnZSIsIkNhblVzZUxvY2F0aW9uUGFnZSIsIkNhblVzZVByb2R1Y3RQYWdlIiwiQ2FuVXNlQmlsbGluZ0FkZHJlc3NQYWdlIiwiQ2FuVXNlQ2FsZW5kYXJIb21lUGFnZSIsIkNhblVzZVByb2ZpbGVDb25maWd1cmF0aW9uUGFnZSIsIkNhblVzZUN1c3RvbWVyVXNlcnNQYWdlIiwiQ2FuVXNlQ29udGFjdFN1cHBvcnQiLCJDYW5Vc2VTZWxlY3RMb2NhdGlvbkNhcnJpZXJQYWdlIiwiQ2FuVXNlUGFzdFF1b3RlIiwiQ2FuVXNlQnVsa1VwbG9hZEFkZHJlc3NQYWdlIiwiQ2FuVXNlUXVpY2tCb2xQYWdlIiwiQ2FuVXNlQnVsa0VkaXRBZGRyZXNzUGFnZSIsIkNhblVzZVRydWNrbG9hZEFwaSIsIkNhblVzZUN1c3RvbWVyQ2FycmllclJlc291cmNlc1BhZ2UiLCJDYW5Vc2VCdWxrVXBsb2FkT3JkZXJQYWdlIiwiQ2FuVXNlSW52b2ljZVBhZ2UiLCJDdXN0b21lckFkbWluaXN0cmF0b3IiXSwibmJmIjoxNjU2NTI4NzgwLCJleHAiOjE2NTY1MzIzODAsImlhdCI6MTY1NjUyODc4MH0.8jlw6pcQBQMgFJeY0yvaJPIA30grpUoSqoqX_iOPH6U' \
	//   -H 'cache-control: no-cache' \
	//   -H 'content-type: application/json' \
	//   -H 'cookie: ai_user=Oi4VWkdRdayuaM8bsUTtLr|2022-05-12T16:52:15.909Z; _gcl_au=1.1.611107233.1655681811; ASPSESSIONIDSGBBABTD=NPLCKCCDJJODINFPGLADMIMB; ASPSESSIONIDSGBDSDSS=FABDOGMAPFILKLMJLDGKJLGL; ASPSESSIONIDQGBCCATD=JNHDFMLAOENHAOHFCOCFEGAB; _gid=GA1.2.419302534.1656369639; ASPSESSIONIDCERTDBQA=ENICOGMAFEILPOLEFDLHJPMD; ASPSESSIONIDQEBBACTD=BMCCANBBMNJOPJAPPGPCNLKD; ASPSESSIONIDCEDSACSB=LIPOJPGBBDAKNGPMOLIDLPJI; ASPSESSIONIDSGCDDDQD=AHBDLLIBNMBGNJNIOMNBDMHC; ASPSESSIONIDCEAQABQD=MEFJLFMBGGFJIJIHOCBHELJB; ASPSESSIONIDCWSDADCC=OAHILFMBDLKECGMMKPLGNLAG; ASPSESSIONIDQEBCBBTC=BKGNLFMBMJHBJEONDOHIFFLC; __hstc=192659957.8a5120f2ac7e92bcbc4d024d24496121.1656523539480.1656523539480.1656523539480.1; hubspotutk=8a5120f2ac7e92bcbc4d024d24496121; __hssrc=1; intercom-id-c9oc6fab=6061889f-d64f-4ae3-bfbd-9679a1684748; ASPSESSIONIDSGTSAQSQ=GFOLFIBCDJPICKNKGDEOLCHN; _ga=GA1.1.2101301807.1655681811; intercom-session-c9oc6fab=eklsV0JUWEk0Zml6Zzhoc2V5eWxzNXllc3VVemcwODRIc1Q4MDBQSmFnVUpnQTlBZCtYaWVUcXRsMFpYbWRLRy0tYXJDdDg1MHZPcHlsMktwRmpBakZwUT09--067261c677ad7fc0ee9a0e5976119b03ab55e3a0; _ga_7EFE8PPXQV=GS1.1.1656523538.42.1.1656525472.0; ASPSESSIONIDQUBTTTAD=MEBAGIBCFBLBMAGOONDGOBJG; ai_session=rpaTQOXn6PRWOSEYKKMzyi|1656523538398|1656529590945; _gat_UA-114313627-1=1' \
	//   -H 'dnt: 1' \
	//   -H 'environment: PROD' \
	//   -H 'notificationresponseurl: https://inf-prod-signalrhandler.azurewebsites.net/' \
	//   -H 'orderprocessingurl: https://app-orderprocessing-prod-bulkapi.azurewebsites.net/' \
	//   -H 'origin: https://rapidshipltl.mycarriertms.com' \
	//   -H 'pragma: no-cache' \
	//   -H 'referer: https://rapidshipltl.mycarriertms.com/customers/shipment?shipmentId=3434436' \
	//   -H 'request-context: appId=cid-v1:cf6939be-b751-46bb-b434-d14afeb50826' \
	//   -H 'request-id: |5b170a9afb684ad8aebce2510c6c2624.cc13eb0a87b447f8' \
	//   -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
	//   -H 'sec-ch-ua-mobile: ?0' \
	//   -H 'sec-ch-ua-platform: "macOS"' \
	//   -H 'sec-fetch-dest: empty' \
	//   -H 'sec-fetch-mode: cors' \
	//   -H 'sec-fetch-site: same-origin' \
	//   -H 'timezone: 420' \
	//   -H 'traceparent: 00-5b170a9afb684ad8aebce2510c6c2624-cc13eb0a87b447f8-01' \
	//   -H 'truckloadfunctionurl: https://app-truckload-prod-api.azurewebsites.net/' \
	//   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
	//   --data-raw '{"ShipmentId":3434436,"OriginLocation":"https://rapidshipltl.mycarriertms.com","SecurityKey":"9339da0d-e629-450b-b7a2-5e757eb5e3d0","CustomerBOLNumber":"customerbol"}' \
	//   --compressed

	type Payload struct {
		ShipmentID        int    `json:"ShipmentId"`
		OriginLocation    string `json:"OriginLocation"`
		SecurityKey       string `json:"SecurityKey"`
		CustomerBOLNumber string `json:"CustomerBOLNumber"`
	}

	data := Payload{
		// fill struct
		ShipmentID:        3434436,
		OriginLocation:    "https://rapidshipltl.mycarriertms.com",
		SecurityKey:       "9339da0d-e629-450b-b7a2-5e757eb5e3d0",
		CustomerBOLNumber: "customerbol",
	}
	payloadBytes, err := json.Marshal(data)
	if err != nil {
		// handle err
	}
	body := bytes.NewReader(payloadBytes)

	req, err := http.NewRequest("POST", "https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/Quote/SaveBolAsPdf", body)
	if err != nil {
		// handle err
	}
	req.Header.Set("Authority", "rapidshipltl.mycarriertms.com")
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	req.Header.Set("Access-Control-Expose-Headers", "Content-Disposition")
	req.Header.Set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImthbmRlbHN1cmVuQGdtYWlsLmNvbSIsInJvbGUiOlsiTXlDYXJyaWVyX1NoaXAiLCJNeUNhcnJpZXJfTWFuYWdlQ29tcGFueSIsIkNhbkFjY2Vzc0hvbWVQYWdlIiwiQ2FuVXNlUXVvdGVQYWdlIiwiQ2FuVXNlU2hpcG1lbnRMaXN0UGFnZSIsIkNhblVzZUFkZHJlc3NCb29rUGFnZSIsIkNhblVzZUxvY2F0aW9uUGFnZSIsIkNhblVzZVByb2R1Y3RQYWdlIiwiQ2FuVXNlQmlsbGluZ0FkZHJlc3NQYWdlIiwiQ2FuVXNlQ2FsZW5kYXJIb21lUGFnZSIsIkNhblVzZVByb2ZpbGVDb25maWd1cmF0aW9uUGFnZSIsIkNhblVzZUN1c3RvbWVyVXNlcnNQYWdlIiwiQ2FuVXNlQ29udGFjdFN1cHBvcnQiLCJDYW5Vc2VTZWxlY3RMb2NhdGlvbkNhcnJpZXJQYWdlIiwiQ2FuVXNlUGFzdFF1b3RlIiwiQ2FuVXNlQnVsa1VwbG9hZEFkZHJlc3NQYWdlIiwiQ2FuVXNlUXVpY2tCb2xQYWdlIiwiQ2FuVXNlQnVsa0VkaXRBZGRyZXNzUGFnZSIsIkNhblVzZVRydWNrbG9hZEFwaSIsIkNhblVzZUN1c3RvbWVyQ2FycmllclJlc291cmNlc1BhZ2UiLCJDYW5Vc2VCdWxrVXBsb2FkT3JkZXJQYWdlIiwiQ2FuVXNlSW52b2ljZVBhZ2UiLCJDdXN0b21lckFkbWluaXN0cmF0b3IiXSwibmJmIjoxNjU2NTI4NzgwLCJleHAiOjE2NTY1MzIzODAsImlhdCI6MTY1NjUyODc4MH0.8jlw6pcQBQMgFJeY0yvaJPIA30grpUoSqoqX_iOPH6U")
	req.Header.Set("Cache-Control", "no-cache")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Cookie", "ai_user=Oi4VWkdRdayuaM8bsUTtLr|2022-05-12T16:52:15.909Z; _gcl_au=1.1.611107233.1655681811; ASPSESSIONIDSGBBABTD=NPLCKCCDJJODINFPGLADMIMB; ASPSESSIONIDSGBDSDSS=FABDOGMAPFILKLMJLDGKJLGL; ASPSESSIONIDQGBCCATD=JNHDFMLAOENHAOHFCOCFEGAB; _gid=GA1.2.419302534.1656369639; ASPSESSIONIDCERTDBQA=ENICOGMAFEILPOLEFDLHJPMD; ASPSESSIONIDQEBBACTD=BMCCANBBMNJOPJAPPGPCNLKD; ASPSESSIONIDCEDSACSB=LIPOJPGBBDAKNGPMOLIDLPJI; ASPSESSIONIDSGCDDDQD=AHBDLLIBNMBGNJNIOMNBDMHC; ASPSESSIONIDCEAQABQD=MEFJLFMBGGFJIJIHOCBHELJB; ASPSESSIONIDCWSDADCC=OAHILFMBDLKECGMMKPLGNLAG; ASPSESSIONIDQEBCBBTC=BKGNLFMBMJHBJEONDOHIFFLC; __hstc=192659957.8a5120f2ac7e92bcbc4d024d24496121.1656523539480.1656523539480.1656523539480.1; hubspotutk=8a5120f2ac7e92bcbc4d024d24496121; __hssrc=1; intercom-id-c9oc6fab=6061889f-d64f-4ae3-bfbd-9679a1684748; ASPSESSIONIDSGTSAQSQ=GFOLFIBCDJPICKNKGDEOLCHN; _ga=GA1.1.2101301807.1655681811; intercom-session-c9oc6fab=eklsV0JUWEk0Zml6Zzhoc2V5eWxzNXllc3VVemcwODRIc1Q4MDBQSmFnVUpnQTlBZCtYaWVUcXRsMFpYbWRLRy0tYXJDdDg1MHZPcHlsMktwRmpBakZwUT09--067261c677ad7fc0ee9a0e5976119b03ab55e3a0; _ga_7EFE8PPXQV=GS1.1.1656523538.42.1.1656525472.0; ASPSESSIONIDQUBTTTAD=MEBAGIBCFBLBMAGOONDGOBJG; ai_session=rpaTQOXn6PRWOSEYKKMzyi|1656523538398|1656529590945; _gat_UA-114313627-1=1")
	req.Header.Set("Dnt", "1")
	req.Header.Set("Environment", "PROD")
	req.Header.Set("Notificationresponseurl", "https://inf-prod-signalrhandler.azurewebsites.net/")
	req.Header.Set("Orderprocessingurl", "https://app-orderprocessing-prod-bulkapi.azurewebsites.net/")
	req.Header.Set("Origin", "https://rapidshipltl.mycarriertms.com")
	req.Header.Set("Pragma", "no-cache")
	req.Header.Set("Referer", "https://rapidshipltl.mycarriertms.com/customers/shipment?shipmentId=3434436")
	req.Header.Set("Request-Context", "appId=cid-v1:cf6939be-b751-46bb-b434-d14afeb50826")
	req.Header.Set("Request-Id", "|5b170a9afb684ad8aebce2510c6c2624.cc13eb0a87b447f8")
	req.Header.Set("Sec-Ch-Ua", "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"102\", \"Google Chrome\";v=\"102\"")
	req.Header.Set("Sec-Ch-Ua-Mobile", "?0")
	req.Header.Set("Sec-Ch-Ua-Platform", "\"macOS\"")
	req.Header.Set("Sec-Fetch-Dest", "empty")
	req.Header.Set("Sec-Fetch-Mode", "cors")
	req.Header.Set("Sec-Fetch-Site", "same-origin")
	req.Header.Set("Timezone", "420")
	req.Header.Set("Traceparent", "00-5b170a9afb684ad8aebce2510c6c2624-cc13eb0a87b447f8-01")
	req.Header.Set("Truckloadfunctionurl", "https://app-truckload-prod-api.azurewebsites.net/")
	req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36")

	resp, err := http.DefaultClient.Do(req)
	datas, err := ioutil.ReadAll(resp.Body)
	fmt.Println(string(datas))
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
}
