package test

import "github.com/ramsfords/backend/firstshipper_backend/business/rapid/models"

type AutoGenerated struct {
	QuoteDetails struct {
		BillingAddress struct {
			AddressID            int         `json:"addressId"`
			PickUpInstructions   interface{} `json:"pickUpInstructions"`
			DeliveryInstructions interface{} `json:"deliveryInstructions"`
			City                 string      `json:"city"`
			CompanyName          string      `json:"companyName"`
			PrimaryContactPerson struct {
				AddressContactID int         `json:"addressContactId"`
				Name             string      `json:"name"`
				Email            string      `json:"email"`
				FirstName        string      `json:"firstName"`
				IsPrimary        bool        `json:"isPrimary"`
				LastName         string      `json:"lastName"`
				Phone            string      `json:"phone"`
				Position         interface{} `json:"position"`
				Ext              interface{} `json:"ext"`
			} `json:"primaryContactPerson"`
			AddressContacts []struct {
				AddressContactID int         `json:"addressContactId"`
				Name             string      `json:"name"`
				FirstName        string      `json:"firstName"`
				LastName         string      `json:"lastName"`
				Phone            string      `json:"phone"`
				Ext              interface{} `json:"ext"`
				Email            string      `json:"email"`
				Position         interface{} `json:"position"`
				IsPrimary        bool        `json:"isPrimary"`
			} `json:"addressContacts"`
			Country          string      `json:"country"`
			CountryCode      string      `json:"countryCode"`
			DeliveryFromTime string      `json:"deliveryFromTime"`
			DeliveryToTime   string      `json:"deliveryToTime"`
			IsCanada         bool        `json:"isCanada"`
			PostalCode       string      `json:"postalCode"`
			ShippingFromTime string      `json:"shippingFromTime"`
			ShippingToTime   string      `json:"shippingToTime"`
			State            string      `json:"state"`
			StateCode        string      `json:"stateCode"`
			StreetLine1      string      `json:"streetLine1"`
			StreetLine2      interface{} `json:"streetLine2"`
			Location         struct {
				AddressID int    `json:"addressId"`
				Name      string `json:"name"`
				IsDefault bool   `json:"isDefault"`
			} `json:"location"`
			CommercialType      interface{}   `json:"commercialType"`
			AddressAccessorials []interface{} `json:"addressAccessorials"`
			Lat                 float64       `json:"lat"`
			Long                float64       `json:"long"`
			BulkAddressID       interface{}   `json:"bulkAddressId"`
			BulkEditGUID        interface{}   `json:"bulkEditGuid"`
			HasSaiaIntegration  bool          `json:"hasSaiaIntegration"`
		} `json:"billingAddress"`
		OriginShippingDetails struct {
			PickupDate string `json:"pickupDate"`
			Address    struct {
				AddressID            int         `json:"addressId"`
				PickUpInstructions   interface{} `json:"pickUpInstructions"`
				DeliveryInstructions interface{} `json:"deliveryInstructions"`
				City                 string      `json:"city"`
				CompanyName          string      `json:"companyName"`
				PrimaryContactPerson struct {
					AddressContactID int         `json:"addressContactId"`
					Name             string      `json:"name"`
					Email            string      `json:"email"`
					FirstName        string      `json:"firstName"`
					IsPrimary        bool        `json:"isPrimary"`
					LastName         string      `json:"lastName"`
					Phone            string      `json:"phone"`
					Position         interface{} `json:"position"`
					Ext              interface{} `json:"ext"`
				} `json:"primaryContactPerson"`
				AddressContacts []struct {
					AddressContactID int         `json:"addressContactId"`
					Name             string      `json:"name"`
					FirstName        string      `json:"firstName"`
					LastName         string      `json:"lastName"`
					Phone            string      `json:"phone"`
					Ext              interface{} `json:"ext"`
					Email            string      `json:"email"`
					Position         interface{} `json:"position"`
					IsPrimary        bool        `json:"isPrimary"`
				} `json:"addressContacts"`
				Country          string      `json:"country"`
				CountryCode      string      `json:"countryCode"`
				DeliveryFromTime string      `json:"deliveryFromTime"`
				DeliveryToTime   string      `json:"deliveryToTime"`
				IsCanada         bool        `json:"isCanada"`
				PostalCode       string      `json:"postalCode"`
				ShippingFromTime string      `json:"shippingFromTime"`
				ShippingToTime   string      `json:"shippingToTime"`
				State            string      `json:"state"`
				StateCode        string      `json:"stateCode"`
				StreetLine1      string      `json:"streetLine1"`
				StreetLine2      interface{} `json:"streetLine2"`
				Location         struct {
					AddressID int         `json:"addressId"`
					Name      interface{} `json:"name"`
					IsDefault bool        `json:"isDefault"`
				} `json:"location"`
				CommercialType struct {
					AccessorialID   int         `json:"accessorialId"`
					Name            string      `json:"name"`
					Code            interface{} `json:"code"`
					DestinationCode interface{} `json:"destinationCode"`
					IsOnlyForCanada bool        `json:"isOnlyForCanada"`
					IsOnlyForUSA    bool        `json:"isOnlyForUSA"`
					DataType        interface{} `json:"dataType"`
					Value           interface{} `json:"value"`
				} `json:"commercialType"`
				AddressAccessorials []interface{} `json:"addressAccessorials"`
				Lat                 float64       `json:"lat"`
				Long                float64       `json:"long"`
				BulkAddressID       interface{}   `json:"bulkAddressId"`
				BulkEditGUID        interface{}   `json:"bulkEditGuid"`
				HasSaiaIntegration  bool          `json:"hasSaiaIntegration"`
			} `json:"address"`
			RequestedDeliveryDate interface{} `json:"requestedDeliveryDate"`
		} `json:"originShippingDetails"`
		DestinationShippingDetails struct {
			Address struct {
				AddressID            int         `json:"addressId"`
				PickUpInstructions   interface{} `json:"pickUpInstructions"`
				DeliveryInstructions interface{} `json:"deliveryInstructions"`
				City                 string      `json:"city"`
				CompanyName          interface{} `json:"companyName"`
				PrimaryContactPerson struct {
					AddressContactID interface{} `json:"addressContactId"`
					Name             interface{} `json:"name"`
					Email            interface{} `json:"email"`
					FirstName        interface{} `json:"firstName"`
					IsPrimary        interface{} `json:"isPrimary"`
					LastName         interface{} `json:"lastName"`
					Phone            interface{} `json:"phone"`
					Position         interface{} `json:"position"`
					Ext              interface{} `json:"ext"`
				} `json:"primaryContactPerson"`
				AddressContacts  interface{} `json:"addressContacts"`
				Country          string      `json:"country"`
				CountryCode      string      `json:"countryCode"`
				DeliveryFromTime interface{} `json:"deliveryFromTime"`
				DeliveryToTime   interface{} `json:"deliveryToTime"`
				IsCanada         bool        `json:"isCanada"`
				PostalCode       string      `json:"postalCode"`
				ShippingFromTime interface{} `json:"shippingFromTime"`
				ShippingToTime   interface{} `json:"shippingToTime"`
				State            string      `json:"state"`
				StateCode        string      `json:"stateCode"`
				StreetLine1      interface{} `json:"streetLine1"`
				StreetLine2      interface{} `json:"streetLine2"`
				Location         interface{} `json:"location"`
				CommercialType   struct {
					AccessorialID   int         `json:"accessorialId"`
					Name            string      `json:"name"`
					Code            interface{} `json:"code"`
					DestinationCode interface{} `json:"destinationCode"`
					IsOnlyForCanada bool        `json:"isOnlyForCanada"`
					IsOnlyForUSA    bool        `json:"isOnlyForUSA"`
					DataType        interface{} `json:"dataType"`
					Value           interface{} `json:"value"`
				} `json:"commercialType"`
				AddressAccessorials []interface{} `json:"addressAccessorials"`
				Lat                 float64       `json:"lat"`
				Long                float64       `json:"long"`
				BulkAddressID       interface{}   `json:"bulkAddressId"`
				BulkEditGUID        interface{}   `json:"bulkEditGuid"`
				HasSaiaIntegration  bool          `json:"hasSaiaIntegration"`
			} `json:"address"`
			RequestedDeliveryDate interface{} `json:"requestedDeliveryDate"`
		} `json:"destinationShippingDetails"`
		ShipmentItems []struct {
			HandlingUnitType   string `json:"handlingUnitType"`
			HandlingUnitNumber int    `json:"handlingUnitNumber"`
			Dimensions         struct {
				Length        string `json:"length"`
				Width         string `json:"width"`
				Height        string `json:"height"`
				CurrentLength string `json:"currentLength"`
				CurrentWidth  string `json:"currentWidth"`
				CurrentHeight string `json:"currentHeight"`
			} `json:"dimensions"`
			Stackable   bool `json:"stackable"`
			Commodities []struct {
				Description        string      `json:"description"`
				Nmfc               interface{} `json:"nmfc"`
				NmfcSub            interface{} `json:"nmfcSub"`
				CommodityClass     string      `json:"commodityClass"`
				Pieces             int         `json:"pieces"`
				TotalWeight        string      `json:"totalWeight"`
				CurrentTotalWeight string      `json:"currentTotalWeight"`
				IsHazardous        bool        `json:"isHazardous"`
				HazmatDetailInfo   struct {
					UnCode             string      `json:"unCode"`
					UnNumber           string      `json:"unNumber"`
					ProperShippingName string      `json:"properShippingName"`
					HazardClass        interface{} `json:"hazardClass"`
					PackingGroup       interface{} `json:"packingGroup"`
					PackingType        string      `json:"packingType"`
					ClassCode          interface{} `json:"classCode"`
					PackingGroupCode   interface{} `json:"packingGroupCode"`
				} `json:"hazmatDetailInfo"`
				CustomerOrderNumber interface{} `json:"customerOrderNumber"`
				AdditionalInfo      interface{} `json:"additionalInfo"`
			} `json:"commodities"`
		} `json:"shipmentItems"`
		FreightCharge             int         `json:"freightCharge"`
		ShipmentID                interface{} `json:"shipmentId"`
		IsInsuredShipment         bool        `json:"isInsuredShipment"`
		InsuranceEditShipmentData interface{} `json:"insuranceEditShipmentData"`
		CarrierCode               interface{} `json:"carrierCode"`
		ReferenceNumberInfo       struct {
		} `json:"referenceNumberInfo"`
		EmergencyContactPerson struct {
			Name  string `json:"name"`
			Phone string `json:"phone"`
		} `json:"emergencyContactPerson"`
		ServiceLevelCode               interface{}              `json:"serviceLevelCode"`
		IsAdminQuote                   bool                     `json:"isAdminQuote"`
		ReferenceID                    interface{}              `json:"referenceId"`
		IsFromSavedQuote               bool                     `json:"isFromSavedQuote"`
		IsFromShipment                 bool                     `json:"isFromShipment"`
		SpecialInstructionDefaultText  interface{}              `json:"specialInstructionDefaultText"`
		ServiceType                    int                      `json:"serviceType"`
		IsShowVLTLToggle               bool                     `json:"isShowVLTLToggle"`
		LinearFeet                     interface{}              `json:"linearFeet"`
		CurrentLinearFeet              interface{}              `json:"currentLinearFeet"`
		IsVLTLResponse                 bool                     `json:"isVLTLResponse"`
		IsAutoEmailTrackingEnabled     bool                     `json:"isAutoEmailTrackingEnabled"`
		IsManualDispatchSettingEnabled bool                     `json:"isManualDispatchSettingEnabled"`
		IsMetricMeasurementEnabled     bool                     `json:"isMetricMeasurementEnabled"`
		EquipmentTypeID                interface{}              `json:"equipmentTypeId"`
		EquipmentTypeName              interface{}              `json:"equipmentTypeName"`
		EquipmentSize                  interface{}              `json:"equipmentSize"`
		TargetRate                     interface{}              `json:"targetRate"`
		ShipmentNote                   interface{}              `json:"shipmentNote"`
		IsHotLoad                      bool                     `json:"isHotLoad"`
		OpportunityID                  interface{}              `json:"opportunityId"`
		OptionID                       interface{}              `json:"optionId"`
		TruckloadAccessorials          interface{}              `json:"truckloadAccessorials"`
		QuoteID                        int                      `json:"quoteId"`
		QuoteOpportunityID             interface{}              `json:"quoteOpportunityId"`
		ShipmentTruckloadID            interface{}              `json:"shipmentTruckloadId"`
		IsReRunShipment                bool                     `json:"isReRunShipment"`
		SpecialInstruction             string                   `json:"specialInstruction"`
		CarriersNotInQuote             models.CarrierNotInQuote `json:"carriersNotInQuote"`
		QuoteKey                       interface{}              `json:"quoteKey"`
		IsExistConnectedCarriers       bool                     `json:"isExistConnectedCarriers"`
		IsCargoInsuranceToogleOn       bool                     `json:"isCargoInsuranceToogleOn"`
		CargoInsuranceQuoteInfo        struct {
			IsAllowedPromptForCargoValue bool `json:"isAllowedPromptForCargoValue"`
			MaxCargoValue                int  `json:"maxCargoValue"`
			AdminCargoInsuranceInfo      struct {
				IntegrationFee    int     `json:"integrationFee"`
				LtlMinimumPremium int     `json:"ltlMinimumPremium"`
				PremiumRate       float64 `json:"premiumRate"`
			} `json:"adminCargoInsuranceInfo"`
			CustomerIntegrationFee              int  `json:"customerIntegrationFee"`
			IsInsureShipmentsEnabledByCarrier   bool `json:"isInsureShipmentsEnabledByCarrier"`
			IsSaiaCustomer                      bool `json:"isSaiaCustomer"`
			CarrierIntegrationFee               int  `json:"carrierIntegrationFee"`
			CarrierInsuranceCoeffecientCoverage int  `json:"carrierInsuranceCoeffecientCoverage"`
		} `json:"cargoInsuranceQuoteInfo"`
		QuoteErrors                      []interface{} `json:"quoteErrors"`
		UnusedCommodities                []interface{} `json:"unusedCommodities"`
		CustomerCarrierID                int           `json:"customerCarrierId"`
		IntegratedLocationAccountNumber1 interface{}   `json:"integratedLocationAccountNumber1"`
		TimeCreated                      interface{}   `json:"timeCreated"`
		OriginCode                       interface{}   `json:"originCode"`
		TruckloadCapacityProviders       []string      `json:"truckloadCapacityProviders"`
		IsVicsBolShipment                bool          `json:"isVicsBolShipment"`
		TotalWeight                      string        `json:"totalWeight"`
		CurrentEquipmentSize             interface{}   `json:"currentEquipmentSize"`
		QuoteDate                        string        `json:"quoteDate"`
	} `json:"quoteDetails"`
	ConfirmAndDispatch interface{} `json:"confirmAndDispatch"`
	QuoteRate          struct {
		IsValid       bool `json:"isValid"`
		TitleHeadData struct {
			AccessorialServices []interface{} `json:"accessorialServices"`
			OriginZip           string        `json:"originZip"`
			DestinationZip      string        `json:"destinationZip"`
			Weight              int           `json:"weight"`
			QuoteKey            string        `json:"quoteKey"`
			Classes             []string      `json:"classes"`
			PickUpDate          string        `json:"pickUpDate"`
			FormatedPickUpDate  struct {
				FormatedDay     string `json:"formatedDay"`
				FormatedWeekDay string `json:"formatedWeekDay"`
				FormatedMonth   string `json:"formatedMonth"`
			} `json:"formatedPickUpDate"`
		} `json:"titleHeadData"`
		QuoteID            int           `json:"quoteId"`
		ErrorMessages      []interface{} `json:"errorMessages"`
		CarriersNotInQuote []interface{} `json:"carriersNotInQuote"`
		DayDeliveries      []struct {
			FormatedGuaranteedDate      string      `json:"formatedGuaranteedDate"`
			GuarantedDate               string      `json:"guarantedDate"`
			IsHoliday                   bool        `json:"isHoliday"`
			IsWeekend                   bool        `json:"isWeekend"`
			HolidayName                 interface{} `json:"holidayName"`
			IsUnspecifiedTransitCarrier bool        `json:"isUnspecifiedTransitCarrier"`
			DayDeliveryFormated         struct {
				FormatedDay     string `json:"formatedDay"`
				FormatedWeekDay string `json:"formatedWeekDay"`
				FormatedMonth   string `json:"formatedMonth"`
			} `json:"dayDeliveryFormated"`
			TransitDays int `json:"transitDays"`
			Standart    []struct {
				CarrierCode                  string      `json:"carrierCode"`
				CarrierCodeAdditional        string      `json:"carrierCodeAdditional"`
				CarrierName                  string      `json:"carrierName"`
				NetworkPartnerID             interface{} `json:"networkPartnerId"`
				IsGuaranty                   bool        `json:"isGuaranty"`
				CarrierDeliveryDate          string      `json:"carrierDeliveryDate"`
				CarrierDeliveryTime          interface{} `json:"carrierDeliveryTime"`
				EstimateDeliveryDate         string      `json:"estimateDeliveryDate"`
				DeliveryTime                 interface{} `json:"deliveryTime"`
				CapacityProviderQuoteNumber  string      `json:"capacityProviderQuoteNumber"`
				TruckloadIconLogo            interface{} `json:"truckloadIconLogo"`
				CapacityProviderAccountGroup struct {
					Code     string `json:"code"`
					Accounts []struct {
						Code string `json:"code"`
					} `json:"accounts"`
				} `json:"capacityProviderAccountGroup"`
				CarrierRequiredField struct {
					CarrierRequiredFieldID int  `json:"carrierRequiredFieldId"`
					ShipperEmailAddress    bool `json:"shipperEmailAddress"`
					ConsigneeEmailAddress  bool `json:"consigneeEmailAddress"`
					ShipperLastName        bool `json:"shipperLastName"`
					ConsigneeLastName      bool `json:"consigneeLastName"`
					NmfcCode               bool `json:"nmfcCode"`
					ConsigneeTime          bool `json:"consigneeTime"`
				} `json:"carrierRequiredField"`
				CarrierAPIs struct {
					CarrierAPIID             int  `json:"carrierAPIId"`
					QuotingAPIEnabled        bool `json:"quotingAPIEnabled"`
					DispatchAPIEnabled       bool `json:"dispatchAPIEnabled"`
					TrackingAPIEnabled       bool `json:"trackingAPIEnabled"`
					DocumentImagesAPIEnabled bool `json:"documentImagesAPIEnabled"`
				} `json:"carrierAPIs"`
				OnTimeRisk                  float64     `json:"onTimeRisk"`
				Logo                        string      `json:"logo"`
				LargeLogo                   string      `json:"largeLogo"`
				QuoteNumber                 string      `json:"quoteNumber"`
				InfoMessage                 interface{} `json:"infoMessage"`
				CurrencyCode                string      `json:"currencyCode"`
				Total                       float64     `json:"total"`
				ServiceName                 interface{} `json:"serviceName"`
				BolText                     interface{} `json:"bolText"`
				CarrierID                   int         `json:"carrierId"`
				IsTermsAndConditionsEnabled bool        `json:"isTermsAndConditionsEnabled"`
				TermAndCondition            interface{} `json:"termAndCondition"`
				LaneType                    int         `json:"laneType"`
				LaneTypeName                string      `json:"laneTypeName"`
				RateQuoteDetails            []struct {
					Amount           float64     `json:"amount"`
					Rate             float64     `json:"rate"`
					ItemFreightClass interface{} `json:"itemFreightClass"`
					Code             string      `json:"code"`
					Description      string      `json:"description"`
				} `json:"rateQuoteDetails"`
				ServiceLevelCode          string      `json:"serviceLevelCode"`
				IsSelectedCarrier         bool        `json:"isSelectedCarrier"`
				TransitDays               int         `json:"transitDays"`
				DispatchTypeID            interface{} `json:"dispatchTypeId"`
				EffectiveDate             interface{} `json:"effectiveDate"`
				UnAcceptedAccessorials    interface{} `json:"unAcceptedAccessorials"`
				CarrierVolumeQuoteNum     interface{} `json:"carrierVolumeQuoteNum"`
				ContractID                interface{} `json:"contractId"`
				ExpirationDate            interface{} `json:"expirationDate"`
				TruckloadAvailabilityDate interface{} `json:"truckloadAvailabilityDate"`
				PriorityMessageHeading    interface{} `json:"priorityMessageHeading"`
				PriorityMessages          interface{} `json:"priorityMessages"`
				DisplayAPIWarning         bool        `json:"displayAPIWarning"`
				IsHasITMContract          bool        `json:"isHasITMContract"`
				APIOutageMessage          string      `json:"apiOutageMessage"`
			} `json:"standart"`
			GuarantyAM []interface{} `json:"guarantyAM"`
			GuarantyPM []interface{} `json:"guarantyPM"`
		} `json:"dayDeliveries"`
		SelectedCarrier            interface{} `json:"selectedCarrier"`
		SelectedCarrierTransitTime interface{} `json:"selectedCarrierTransitTime"`
	} `json:"quoteRate"`
	Step                          int           `json:"step"`
	SavedQuoteID                  interface{}   `json:"savedQuoteId"`
	ReferenceID                   string        `json:"referenceId"`
	IsFromSavedQuote              bool          `json:"isFromSavedQuote"`
	PickupDate                    string        `json:"pickupDate"`
	InfoMessage                   interface{}   `json:"infoMessage"`
	IsFavorite                    bool          `json:"isFavorite"`
	IsSystemAdmin                 bool          `json:"isSystemAdmin"`
	IsKeepAdminChangesModeEnabled bool          `json:"isKeepAdminChangesModeEnabled"`
	OrderID                       interface{}   `json:"orderId"`
	QuoteErrors                   []interface{} `json:"quoteErrors"`
}
