package models

type ConfirmAndDispatch struct {
	CapacityProviderAccountGroup CapacityProviderAccountGroup `json:"capacityProviderAccountGroup"`
	CapacityProviderQuoteNumber  *string                      `json:"capacityProviderQuoteNumber"`
	CarrierCode                  *string                      `json:"carrierCode"`
	CarrierCodeAdditional        *string                      `json:"carrierCodeAdditional"`
	ShipperDetails               PartyDetails                 `json:"shipperDetails"`
	ConsigneeDetails             PartyDetails                 `json:"consigneeDetails"`
	BillingAddress               Address                      `json:"billingAddress"`
	HandlingUnits                []*ShipmentItem              `json:"handlingUnits,omitempty"`
	ShipmentItems                []*ShipmentItem              `json:"shipmentItems,omitempty"`
	HandlingUnitVolume           float64                      `json:"handlingUnitVolume"`
	HandlingUnitDensity          float64                      `json:"handlingUnitDensity"`
	HandlingUnitTotal            int                          `json:"handlingUnitTotal"`
	TotalCost                    float64                      `json:"totalCost"`
	EstimateDeliveryDate         *string                      `json:"estimateDeliveryDate"`
	CarrierName                  *string                      `json:"carrierName"`
	ServiceName                  *string                      `json:"serviceName"`
	HandlingUnitTotalPackages    int                          `json:"handlingUnitTotalPackages"`
	TotalShipmentWeight          int                          `json:"totalShipmentWeight"`
	IconLogo                     *string                      `json:"iconLogo"`
	CarrierDeliveryDate          *string                      `json:"carrierDeliveryDate"`
	IsGuaranty                   bool                         `json:"isGuaranty"`
	FreightCharge                int                          `json:"freightCharge"`
	BolText                      *string                      `json:"bolText"`
	QuoteID                      int                          `json:"quoteId"`
	OriginLocationID             int                          `json:"originLocationId"`
	DestinationLocationID        int                          `json:"destinationLocationId"`
	BillingAddressID             int                          `json:"billingAddressId"`
	CarrierID                    int                          `json:"carrierId"`
	LaneType                     int                          `json:"laneType"`
	TransitTime                  int                          `json:"transitTime"`
	ShipmentID                   *string                      `json:"shipmentId"`
	ServiceLevelCode             *string                      `json:"serviceLevelCode"`
	SpecialInstruction           *string                      `json:"specialInstruction"`
	ShipmentPriceDetails         *[]RateQuoteDetails          `json:"shipmentPriceDetails,omitempty"`
	RateQuoteDetails             *[]RateQuoteDetails          `json:"rateQuoteDetails,omitempty"`
	ServiceType                  int                          `json:"serviceType"`
	LinearFeet                   interface{}                  `json:"linearFeet"`
	UnAcceptedAccessorials       []*AddressAccessorial        `json:"unAcceptedAccessorials"`
	DispatchTypeID               interface{}                  `json:"dispatchTypeId"`
	EquipmentTypeID              interface{}                  `json:"equipmentTypeId"`
	EquipmentSize                interface{}                  `json:"equipmentSize"`
	TargetRate                   interface{}                  `json:"targetRate"`
	ShipmentNote                 interface{}                  `json:"shipmentNote"`
	IsHotLoad                    bool                         `json:"isHotLoad"`
	OpportunityID                int                          `json:"opportunityId"`
	OptionID                     interface{}                  `json:"optionId"`
	TruckloadAccessorials        interface{}                  `json:"truckloadAccessorials"`
	ShipmentTruckloadID          interface{}                  `json:"shipmentTruckloadId"`
	CargoValue                   interface{}                  `json:"cargoValue"`
	IsFromSavedQuote             bool                         `json:"isFromSavedQuote"`
	IsVicsBolShipment            bool                         `json:"isVicsBolShipment"`
	OriginCode                   interface{}                  `json:"originCode"`
	ReferenceID                  interface{}                  `json:"referenceId"`
	ReferenceNumberInfo          ReferenceNumberInfo          `json:"referenceNumberInfo"`
	EmergencyContactPerson       EmergencyContactPerson       `json:"emergencyContactPerson"`
	BookedDate                   *string                      `json:"bookedDate,omitempty"`
	SavedQuoteID                 *string                      `json:"savedQuoteId,omitempty"`
}
