env: prod
sitessettings:
  menuloom:
    dev:
      servicename: menuloom-dev
      servicefullname: github.com/ramsfords/menuloom-dev
      version: 0.0.1
      enablesignup: true
      domain: http://127.0.0.1:8090
      backenddomain: http://127.0.0.1:8090
      apidomain: http://127.0.0.1:8090
      frontendurl: http://127.0.0.1:3000
      emailid: quotes@firstshipper.com
    prod:
      servicename: menuloom-prod
      servicefullname: github.com/ramsfords/menuloom_backend
      version: 0.0.1
      enablesignup: true
      domain: menuloom.com
      backenddomain: backend.menuloom.com
      apidomain: api.menuloom.com
      frontendurl: https://menuloom.com
      emailid: quotes@firstshipper.com
    dynamodb:
      prodtable: menuloom-prod
      devtable: menuloom-dev
      pkprefix: pk#
      skprefix: sk#
    supabase:
      name: firstshipper-auth
      password: FirstShipper@2023
      url: https://tzqmwwkdggdqbwfyjaii.supabase.co
      publickey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cW13d2tkZ2dkcWJ3ZnlqYWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzQ3NTg5MzMsImV4cCI6MTk5MDMzNDkzM30.mXrR7ETU7mnmprW1Yoqu4appcfiBH3NjgVOIM68SE1c
      servicerole: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6cW13d2tkZ2dkcWJ3ZnlqYWlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NDc1ODkzMywiZXhwIjoxOTkwMzM0OTMzfQ.pkXJDDXXz_AdzA3UAmm6LEjBc03Sikekop0-2M9-pJ0
      jwtsecret: b2NDOA4TjXNCjPVJzLmyRdWOWaJYOEj9vmt5ctosW021j1TWX0LvlGHnOndrG7msl2gtYyp76gcHxrM9GRXnHg==

    email:
      smtphost: smtp.zoho.com
      smtpport: 587
      username: quotes@firstshipper.com
      password: Quotes@14812
      fromemail: quotes@firstshipper.com
      fromname: surendra kandel
      clientid: 1000.YBSL4AA8KH962RLBKGNVPSJHMR3HUC
      clientsecret: 862108cd0338969f306e7b75db28944e49ffd060d3
      accountid: 8292793000000008002
      baseurl: https://accounts.zoho.com
    cloudflareconfig:
      apikey: e518c3520cb2b8cea1c10c658f598a9fba09a
      email: rakeshneupane2045@gmail.com
      accountid: 9bdb1c68b134f76df079a9bcecb24492
      namespaceId: 2eb697aaa3e5456e838590e16e1902e6
    cloudinaryconfig:
      cloudname: dqmotdht5
      apikey: 965891394982642
      apisecret: Pl6Ff5zJSeL5ROQqQojHjindlAg
  firstshipper:
    dev:
      servicename: firstshipper-dev
      servicefullname: github.com/ramsfords/firstshipper-dev
      version: 0.0.1
      enablesignup: true
      domain: http://127.0.0.1:8090
      backenddomain: http://127.0.0.1:8090
      apidomain: http://127.0.0.1:8090
      frontendurl: http://127.0.0.1:3000
      emailid: quotes@firstshipper.com
    prod:
      servicename: firstshipper-prod
      servicefullname: github.com/ramsfords/firstshipper_backend
      version: 0.0.1
      enablesignup: true
      domain: firstshipper.com
      backenddomain: backend.firstshipper.com
      apidomain: api.firstshipper.com
      frontendurl: https://firstshipper.com
      emailid: quotes@firstshipper.com
    dynamodb:
      prodtable: firstshipper-prod
      devtable: firstshipper-dev
      pkprefix: pk#
      skprefix: sk#
    email:
      smtphost: smtp.zoho.com
      smtpport: 587
      username: quotes@firstshipper.com
      password: Quotes@14812
      fromemail: quotes@firstshipper.com
      fromname: surendra kandel
      clientid: 1000.YBSL4AA8KH962RLBKGNVPSJHMR3HUC
      clientsecret: 862108cd0338969f306e7b75db28944e49ffd060d3
      accountid: 8292793000000008002
      baseurl: https://accounts.zoho.com
    emailconf: 
      sendername: first shipper
      senderemail: quotes@firstshipper.com
    quotecountincreaseby: 5
    rapidshipltl:
      companyname: ""
      username: kandelsuren@gmail.com
      password: Priya@1234
      authtokenname: authorization
      authurl: https://mycarriertms.com/MyCarrierAPI//api/TOKEN
      rateurl: https://mycarriertms.com/MyCarrierAPI//api/Quote/GetQuoteRates
      addaddressurl : https://mycarriertms.com/MyCarrierAPI//api/AddressBook/AddAddress
      getaddressurl: https://mycarriertms.com/MyCarrierAPI//api/AddressBook/GetAddresses
      quotehistoryurl: https://mycarriertms.com/MyCarrierAPI//api/SaveQuote/GetSaveQuotes
      dispatchurl: https://mycarriertms.com/MyCarrierAPI//api/Quote/Dispatch
      savequoteurl: https://mycarriertms.com/MyCarrierAPI//api/Quote/SaveQuoteStep
      cancelshipmenturl: https://mycarriertms.com/MyCarrierAPI//api/Shipment/CancelShipment
    schneider:
      companyname: ""
      username: kandelsuren@gmail.com
      password: Priya@1234
      authtokenname: authorization
      authurl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/TOKEN
      rateurl: https://api.schneider.com/external/005/oh/v1/api/v1/quotes/rates/ltl
      addaddressurl : https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/AddressBook/AddAddress
      getaddressurl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/AddressBook/GetAddresses
      quotehistoryurl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/SaveQuote/GetSaveQuotes
      dispatchurl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/Quote/Dispatch
      savequoteurl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/Quote/SaveQuoteStep
      cancelshipmenturl: https://rapidshipltl.mycarriertms.com/MyCarrierAPI//api/Shipment/CancelShipment
    cloudflareconfig:
      apikey: e518c3520cb2b8cea1c10c658f598a9fba09a
      email: rakeshneupane2045@gmail.com
      accountid: 9bdb1c68b134f76df079a9bcecb24492
      namespaceId: c1937ecfe3b04d3b962cc17b49636dca
    cloudinaryconfig:
      cloudname: dqmotdht5
      apikey: 965891394982642
      apisecret: Pl6Ff5zJSeL5ROQqQojHjindlAg
zoho:
  zohocode: 1000.b3ab46622369d647c627c76535c4cbfc.b11bd50f6eb74d550c03ac7096a79f42
  zohoorgid: 802796121
  zohoclientid: 1000.KJJO38B48HHUXDBGUEL3H1IC4T9A2G
  zohoclientsecret: fe1f2d13519786aacf4893f4d3d7ff85ed62d9258e
newrelic:
  appname: grpcauth
  enabled: true
  license: 63b6f32a332f7900564a89674bfd9c3d6860NRAL
server:
  hostname: app
  grpcport: 8091
  httpport: 8091
  debugport: 8092
  timeout: 5
aws:
  credentials:
    apikey: AKIAXDXXNOPF47ZKB3MA
    secretkey: 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
logger:
  outputPath: stdout
  level: info
  disableStackTrace: false
sendinblue:
  apikey: xkeysibs-ad8ff5f481dd0d6c17e4db5b85f0aa3ff2b40545b4da75a36bd9c47596dcd04a-8tTzCwbXDasMA67O
zipkin:
  reporteruri: http://0.0.0.0:9411/api/v2/spans
  servicename:  userservice
  probability: 1
scylladb:
  name: AWS_US_EAST_1
  public: [node-0.aws_us_east_1.77dea567affbe87f2d34.clusters.scylla.cloud, node-1.aws_us_east_1.77dea567affbe87f2d34.clusters.scylla.cloud, node-2.aws_us_east_1.77dea567affbe87f2d34.clusters.scylla.cloud]
  username: scylla
  password: RBEqQuG9be42KVf
  region: AWS_US_EAST_1
  keyspace: menuloom
pdfrenderer:
  apikey: rakeshneupane2045@gmail.com_1cabd4bc5f92a9cea1cf5966a3db7e7760f3ca5f087337815d0bf2bf35780a54a6f0d6ef
  url: https://api.pdf.co/v1/pdf/convert/from/url
  fromhtml: https://api.pdf.co/v1/pdf/convert/from/html
